### ISSUE TITLE
Feature: Allow verifying hostname from JWT

### ISSUE THREAD

**Issue by stefanfoulis** [muhgumus/traefik-token-middleware#3]
If the JWT contains a list of hosts it allows to access, this middleware could deny requests that are not in that list.

**Comment by muhgumus** [comment]
JWT middleware doens not contains a list of hosts it allows to access. 
Traefik middleware configuration contains JWT secret and roles etc. 

traefik auth middleware yaml like below
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: managementportal-jwtauth
spec:
  plugin:
    traefik-token-middleware:
      queryTokenParam: apigotoken
      querytenantIdParam: var-tenantId_pg
      roles: "TenantAdmin,SuperAdmin,DocumentAdmin,EndPointAdmin,ConfigurationAdmin,RestrictionAdmin"
      secret: YourJWTSecret
```
